//DUMMY TEST CODE FOR TESTING BUILD PROCESS

// int main() {
//     // Seed the random number generator
//     srand(time(NULL));

//     // Initialize the onboard LED
//     gpio_init(PICO_DEFAULT_LED_PIN);
//     gpio_set_dir(PICO_DEFAULT_LED_PIN, GPIO_OUT);

//     // Create FreeRTOS tasks
//     xTaskCreate(vTemperatureTask, "Temperature Task", 256, NULL, 1, NULL);
//     xTaskCreate(vBlinkTask, "Blink Task", 128, NULL, 1, NULL);

//     // Start the FreeRTOS scheduler
//     vTaskStartScheduler();

//     // This point should never be reached
//     while (1) {}
// }



// #include "pico/stdlib.h"
// #include "FreeRTOS.h"
// #include "task.h"

// void vBlinkTask() {
//     for (;;) {
//         gpio_put(PICO_DEFAULT_LED_PIN, 1);
//         vTaskDelay(250);
//         gpio_put(PICO_DEFAULT_LED_PIN, 0);
//         vTaskDelay(250);
//     }
// }

// void main() {
//     gpio_init(PICO_DEFAULT_LED_PIN);
//     gpio_set_dir(PICO_DEFAULT_LED_PIN, GPIO_OUT);
//     xTaskCreate(vBlinkTask, "Blink Task", 128, NULL, 1, NULL);
//     vTaskStartScheduler();
// }




// TESTING CODE: TEMPERATURE IS GENERATED BY rand() function

// #include "pico/stdlib.h"
// #include "FreeRTOS.h"
// #include "task.h"
// #include <stdlib.h> // Include this for rand()
// #include <time.h>   // Include this for srand() and time()

// #define HIGH_TEMP_THRESHOLD 30.0f // Temperature threshold in degrees Celsius
// volatile bool high_temp_detected = false; // Shared flag for temperature status

// // Simulate temperature checking task
// void vTemperatureTask(void *pvParameters) {
//     while (1) {
//         // Simulate temperature reading (randomly set high_temp_detected)
//         high_temp_detected = (rand() % 100) < 50; // Simulates 50% chance of high temperature

//         // Delay before the next temperature check
//         vTaskDelay(pdMS_TO_TICKS(1000)); // 1-second delay
//     }
// }

// // Task to blink LED if high temperature is detected
// void vBlinkTask(void *pvParameters) {
//     while (1) {
//         if (high_temp_detected) {
//             gpio_put(PICO_DEFAULT_LED_PIN, 1); // Turn LED on
//             vTaskDelay(pdMS_TO_TICKS(250)); // LED on for 250 ms
//             gpio_put(PICO_DEFAULT_LED_PIN, 0); // Turn LED off
//             vTaskDelay(pdMS_TO_TICKS(250)); // LED off for 250 ms
//         } else {
//             gpio_put(PICO_DEFAULT_LED_PIN, 0); // Ensure LED stays off
//             vTaskDelay(pdMS_TO_TICKS(500)); // Idle delay when temp is normal
//         }
//     }
// }


// ACTUAL CODE THAT MONITORS TEMPERATURE IF ITS ABOVE CERTAIN THRESHOLD (threshold can be changed as you like)

#include "pico/stdlib.h"
#include "FreeRTOS.h"
#include "task.h"
#include "hardware/adc.h"

#define HIGH_TEMP_THRESHOLD 10.0f // Temperature threshold in degrees Celsius
volatile bool high_temp_detected = false; // Shared flag for temperature status

// Task to read the temperature sensor
void vTemperatureTask(void *pvParameters) {
    // Initialize the ADC for temperature reading
    adc_init();
    adc_set_temp_sensor_enabled(true);
    adc_select_input(4); // Select temperature sensor input

    while (1) {
        uint16_t result = adc_read(); // Read raw ADC value
        float voltage = result * 3.3f / (1 << 12); // Convert to voltage
        float temperature = 27.0f - (voltage - 0.706f) / 0.001721f; // Convert to Celsius

        // Check if temperature exceeds threshold
        high_temp_detected = (temperature >= HIGH_TEMP_THRESHOLD);

        // Delay before the next temperature check
        vTaskDelay(pdMS_TO_TICKS(1000)); // 1-second delay
    }
}

// Task to blink LED if high temperature is detected
void vBlinkTask(void *pvParameters) {
    while (1) {
        if (high_temp_detected) {
            gpio_put(PICO_DEFAULT_LED_PIN, 1); // Turn LED on
            vTaskDelay(pdMS_TO_TICKS(250)); // LED on for 250 ms
            gpio_put(PICO_DEFAULT_LED_PIN, 0); // Turn LED off
            vTaskDelay(pdMS_TO_TICKS(250)); // LED off for 250 ms
        } else {
            gpio_put(PICO_DEFAULT_LED_PIN, 0); // Ensure LED stays off
            vTaskDelay(pdMS_TO_TICKS(500)); // Idle delay when temp is normal
        }
    }
}

int main() {
    // Initialize the onboard LED
    gpio_init(PICO_DEFAULT_LED_PIN);
    gpio_set_dir(PICO_DEFAULT_LED_PIN, GPIO_OUT);

    // Create FreeRTOS tasks
    xTaskCreate(vTemperatureTask, "Temperature Task", 256, NULL, 1, NULL);
    xTaskCreate(vBlinkTask, "Blink Task", 128, NULL, 1, NULL);

    // Start the FreeRTOS scheduler
    vTaskStartScheduler();

    // This point should never be reached
    while (1) {}
}
